### ISSUE TITLE
Entrevista equipo WAR

### ISSUE THREAD

**Issue by williamgl3** [SistemasTecTlaxiaco/actividad-2-entrevista-equipowar#1]
https://drive.google.com/file/d/1SbEMRo4LnmHTJ5NW5qwy-B1V_Gj9qA9f/view?usp=sharing

**Comment by NayeliMoraless** [comment]
Le ponemos una calificación de 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
